name: Release API

# Needs to be fixed once frontend and backend code merged

on:
  workflow_call: 
    inputs:
      account-id:
        required: true
        type: string

permissions:
  contents: write
  security-events: write
  id-token: write

jobs:
  api-deploy:
    name: API Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.account-id }}:role/GithubRunner
        aws-region: "eu-west-1"
        role-session-name: GitHub_to_AWS_via_FederatedOIDC

    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: 8.0.x

    # - name: Publish API
    #   working-directory: ./Backend
    #   run: dotnet publish -c Release --output ./Bundle/api

    # - name: Create ZIP Package
    #   working-directory: ./Bundle
    #   run: |
    #     zip -r deploy_package.zip .

    # - name: Upload API Package
    #   working-directory: ./Bundle
    #   run: aws s3 cp deploy_package.zip s3://${{ inputs.account-id  }}-deploy-bucket

    # - name: Create New API Version
    #   run: aws elasticbeanstalk create-application-version --application-name api-app --source-bundle S3Bucket="${{ inputs.account-id  }}-deploy-bucket",S3Key="deploy_package.zip" --version-label "deploy-${{ github.sha }}" --description "commit-sha-${{ github.sha }}"

    # - name: Deploy API
    #   run: aws elasticbeanstalk update-environment --environment-name api-env --version-label "deploy-${{ github.sha }}"
  