name: "Terraform Apply"

on:
  workflow_call:
    inputs:
      account-id:
        required: true
        type: string

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  terraform-apply:
    name: "Terraform apply"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::${{ inputs.account-id }}:role/GithubRunner
          aws-region: "eu-west-1"
          role-session-name: GitHub_to_AWS_via_FederatedOIDC

      - name: Terraform Init
        id: init
        working-directory: ./Terraform
        run: |
          make init

      - name: Terraform Apply
        id: apply
        working-directory: ./Terraform
        run: |
          make apply